Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2022-11, with the labels that each got.

#45 [장희직] Java vs C++, 1,2,3 더하기 4, 도어맨, 배열 복원하기, 후위 표기식2
  src/main/kotlin/heejik/9week/1, 2, 3 더하기 4.kt
  src/main/kotlin/heejik/9week/Java vs C++.kt
  src/main/kotlin/heejik/9week/도어맨.kt
  src/main/kotlin/heejik/9week/배열 복원하기.kt
  src/main/kotlin/heejik/9week/후위 표기식2.kt
Labels: 희직

#43 [전현수] Java vs C++, 배열 복원하기, 도어맨, 1, 2, 3 더하기 4, 후위 표기식 2
  .idea/inspectionProfiles/Project_Default.xml
  src/main/kotlin/hyunsoo/9week/1, 2, 3 더하기 4.kt
  src/main/kotlin/hyunsoo/9week/Java vs C++.kt
  src/main/kotlin/hyunsoo/9week/도어맨.kt
  src/main/kotlin/hyunsoo/9week/배열 복원하기.kt
  src/main/kotlin/hyunsoo/9week/후위 표기식2.kt
Labels: 현수

#44 [소병희] Java vs C++, 1,2,3 더하기 4, 도어맨, 배열 복원하기, 후위 표기식2
  src/main/kotlin/byeonghee/9week/1 2 3 더하기 4.kt
  src/main/kotlin/byeonghee/9week/Java vs C++.kt
  src/main/kotlin/byeonghee/9week/도어맨.kt
  src/main/kotlin/byeonghee/9week/배열 복원하기.kt
  src/main/kotlin/byeonghee/9week/후위 표기식2.kt
Labels: 병희

#42 [이지민] Java vs C++, 1,2,3 더하기 4, 도어맨, 배열 복원하기, 후위 표기식2
  src/main/kotlin/jimin/9week/1, 2, 3 더하기 4.kt
  src/main/kotlin/jimin/9week/Java vs C++.kt
  src/main/kotlin/jimin/9week/도어맨.kt
  src/main/kotlin/jimin/9week/배열 복원하기.kt
  src/main/kotlin/jimin/9week/후위 표기식2.kt
Labels: 지민

#49 [전현수] 숫자 게임, 달팽이, 햄버거 분배, 병든 나이트
  src/main/kotlin/hyunsoo/10week/달팽이.kt
  src/main/kotlin/hyunsoo/10week/병든 나이트.kt
  src/main/kotlin/hyunsoo/10week/숫자 게임.kt
  src/main/kotlin/hyunsoo/10week/햄버거 분배.kt
Labels: 현수

#48 [소병희] 숫자 게임, 달팽이, 햄버거 분배, 병든 나이트
  src/main/kotlin/byeonghee/10week/달팽이.kt
  src/main/kotlin/byeonghee/10week/병든 나이트.kt
  src/main/kotlin/byeonghee/10week/숫자 게임.kt
  src/main/kotlin/byeonghee/10week/햄버거 분배.kt
Labels: 병희

#47 [이지민] 달팽이, 병든 나이트, 숫자 게임, 햄버거 분해
  src/main/kotlin/jimin/10week/달팽이.kt
  src/main/kotlin/jimin/10week/병든 나이트.kt
  src/main/kotlin/jimin/10week/숫자 게임.kt
  src/main/kotlin/jimin/10week/햄버거 분배.kt
Labels: 지민

#50 [장희직] 숫자 게임, 달팽이, 햄버거 분배, 병든 나이트
  src/main/kotlin/heejik/10week/달팽이.kt
  src/main/kotlin/heejik/10week/병든 나이트.kt
  src/main/kotlin/heejik/10week/숫자 게임.kt
  src/main/kotlin/heejik/10week/햄버거 분배.kt
  src/main/kotlin/heejik/9week/후위 표기식2.kt
Labels: 희직

#54 [소병희] 꽃길, 팰린드롬 만들기, 예산, 왕복
  src/main/kotlin/byeonghee/11week/꽃길.kt
  src/main/kotlin/byeonghee/11week/예산.kt
  src/main/kotlin/byeonghee/11week/왕복.kt
  src/main/kotlin/byeonghee/11week/팰린드롬 만들기.kt
Labels: 병희

#55 [이지민] 팰린드롬 만들기, 예산, 왕복, 꽃길
  src/main/kotlin/jimin/11week/꽃길.kt
  src/main/kotlin/jimin/11week/예산.kt
  src/main/kotlin/jimin/11week/왕복.kt
  src/main/kotlin/jimin/11week/팰린드롬 만들기.kt
Labels: 지민

#52 [전현수] 팰린드롬 만들기, 예산, 왕복, 꽃길
  src/main/kotlin/hyunsoo/11week/꽃길.kt
  src/main/kotlin/hyunsoo/11week/예산.kt
  src/main/kotlin/hyunsoo/11week/왕복.kt
  src/main/kotlin/hyunsoo/11week/팰린드롬 만들기.kt
Labels: 현수

#53 [장희직] 팰린드롬 만들기, 예산, 왕복, 꽃길
  src/main/kotlin/heejik/10week/달팽이.kt
  src/main/kotlin/heejik/10week/숫자 게임.kt
  src/main/kotlin/heejik/11week/꽃길.kt
  src/main/kotlin/heejik/11week/예산.kt
  src/main/kotlin/heejik/11week/왕복.kt
  src/main/kotlin/heejik/11week/팰린드롬 만들기.kt
Labels: 희직
