Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2023-09, with the labels that each got.

#169 [소병희] 겹치는 건 싫어, 쉬운 최단거리, 회전 초밥
  src/main/kotlin/byeonghee/week43/겹치는 건 싫어.kt
  src/main/kotlin/byeonghee/week43/쉬운 최단거리.kt
  src/main/kotlin/byeonghee/week43/회전 초밥.kt
Labels: 병희

#166 [이지민] - 겹치는 건 싫어, 기타리스트, 회전초밥, 쉬운 최단거리
  src/main/kotlin/jimin/43week/겹치는 건 싫어.py
  src/main/kotlin/jimin/43week/기타리스트.py
  src/main/kotlin/jimin/43week/쉬운 최단거리.py
  src/main/kotlin/jimin/43week/회전초밥.py
Labels: 지민

#167 [전현수] - 쉬운 최단거리, 겹치는 건 싫어, 기타리스트, 회전 초밥
  src/main/kotlin/hyunsoo/43week/겹치는 건 싫어.kt
  src/main/kotlin/hyunsoo/43week/기타리스트.kt
  src/main/kotlin/hyunsoo/43week/쉬운 최단거리.kt
  src/main/kotlin/hyunsoo/43week/회전 초밥.kt
Labels: 현수

#168 [장희직] - 겹치는 건 싫어, 쉬운 최단거리, 회전 초밥, 기타리스트
  src/main/kotlin/heejik/43week/겹치는 건 싫어.kt
  src/main/kotlin/heejik/43week/기타리스트.kt
  src/main/kotlin/heejik/43week/쉬운 최단거리.kt
  src/main/kotlin/heejik/43week/회전 초밥.kt
Labels: 희직

#171 [전현수] - 케빈 베이컨의 6단계 법칙, 함께 블록 쌓기, 전구와 스위치, CCW
  src/main/kotlin/hyunsoo/44week/CCW.kt
  src/main/kotlin/hyunsoo/44week/전구와 스위치.kt
  src/main/kotlin/hyunsoo/44week/케빈 베이컨의 6단계 법칙.kt
  src/main/kotlin/hyunsoo/44week/함께 블록 쌓기.kt
Labels: 현수

#174 [소병희] 케빈 베이컨의 6단계 법칙, 전구와 스위치, CCW, 함께 블록 쌓기
  src/main/kotlin/byeonghee/week43/기타리스트.kt
  src/main/kotlin/byeonghee/week44/CCW.kt
  src/main/kotlin/byeonghee/week44/전구와 스위치.kt
  src/main/kotlin/byeonghee/week44/케빈 베이컨의 6단계 법칙.kt
  src/main/kotlin/byeonghee/week44/함께 블록 쌓기.kt
Labels: 병희

#172 [장희직] - 케빈 베이컨의 6단계 법칙, 전구와 스위치, CCW, 함께 블록 쌓기
  src/main/kotlin/heejik/44week/CCW.kt
  src/main/kotlin/heejik/44week/전구와 스위치.kt
  src/main/kotlin/heejik/44week/케빈 베이컨의 6단계 법칙.kt
  src/main/kotlin/heejik/44week/함께 블록 쌓기.kt
Labels: 희직

#179 [이지민] - 연산자 끼워넣기, 게임, 디스크 컨트롤러
  src/main/kotlin/jimin/45week/게임.py
  src/main/kotlin/jimin/45week/디스크 컨트롤러.py
  src/main/kotlin/jimin/45week/연산자 끼워넣기.py
Labels: 지민

#176 [전현수] - A와 B, 게임, 디스크 컨트롤러
  src/main/kotlin/hyunsoo/45week/A와 B.kt
  src/main/kotlin/hyunsoo/45week/게임.kt
  src/main/kotlin/hyunsoo/45week/디스크 컨트롤러.kt
  src/main/kotlin/hyunsoo/45week/연산자 끼워넣기.kt
Labels: 현수

#177 [장희직] - 게임, 연산자 끼워넣기, 디스크 컨트롤러, A와 B
  src/main/kotlin/heejik/45week/A와 B.kt
  src/main/kotlin/heejik/45week/게임.kt
  src/main/kotlin/heejik/45week/연산자 끼워넣기.kt
Labels: 희직
