Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2023-02, with the labels that each got.

#88 [전현수] - 스위치 켜고 끄기, 알파벳, 부등호, 스티커
  src/main/kotlin/hyunsoo/21week/별 찍기 - 13.kt
  src/main/kotlin/hyunsoo/21week/부등호.kt
  src/main/kotlin/hyunsoo/21week/스위치 켜고 끄기.kt
  src/main/kotlin/hyunsoo/21week/스티커.kt
  src/main/kotlin/hyunsoo/21week/알파벳.kt
Labels: 현수

#89 [장희직] - 스위치 켜고 끄기, 알파벳, 부등호, 스티커
  src/main/kotlin/heejik/21week/부등호.kt
  src/main/kotlin/heejik/21week/스위치 켜고 끄기.kt
  src/main/kotlin/heejik/21week/스티커.kt
  src/main/kotlin/heejik/21week/알파벳.kt
Labels: 희직

#90 [이지민] - 스위치 켜고 끄기, 알파벳, 부등호, 스티커
  src/main/kotlin/jimin/21week/부등호.kt
  src/main/kotlin/jimin/21week/스위치 켜고 끄기.kt
  src/main/kotlin/jimin/21week/스티커.kt
  src/main/kotlin/jimin/21week/알파벳.kt
Labels: 지민

#87 [소병희] 알파벳, 부등호, 스위치 켜고 끄기, 스티커
  src/main/kotlin/byeonghee/21week/부등호.kt
  src/main/kotlin/byeonghee/21week/스위치 켜고 끄기.kt
  src/main/kotlin/byeonghee/21week/스티커.kt
  src/main/kotlin/byeonghee/21week/알파벳.kt
  src/main/kotlin/byeonghee/21week/톱니바퀴.kt
Labels: 병희

#94 [이지민] 최소 회의실 개수, ABCDE, 평범한 배낭
  src/main/kotlin/jimin/22week/ABCDE.kt
  src/main/kotlin/jimin/22week/감시 피하기.kt
  src/main/kotlin/jimin/22week/최소 회의실 개수.kt
  src/main/kotlin/jimin/22week/평범한 배낭.kt
Labels: 지민

#95 [전현수] - 감시 피하기, ABCDE, 평범한 배낭, 최소 회의실 개수
  src/main/kotlin/hyunsoo/22week/ABCDE.kt
  src/main/kotlin/hyunsoo/22week/감시 피하기.kt
  src/main/kotlin/hyunsoo/22week/최소 회의실 개수.kt
  src/main/kotlin/hyunsoo/22week/평범한 배낭.kt
Labels: 현수

#92 [소병희] 최소 회의실 개수, ABCDE, 평범한 배낭, 감시 피하기
  src/main/kotlin/byeonghee/22week/ABCDE.kt
  src/main/kotlin/byeonghee/22week/감시 피하기.kt
  src/main/kotlin/byeonghee/22week/최소 회의실 개수.kt
  src/main/kotlin/byeonghee/22week/평범한 배낭.kt
Labels: 병희

#93 [장희직] 최소 회의실 개수, ABCDE, 평범한 배낭, 감시 피하기
  src/main/kotlin/heejik/21week/스위치 켜고 끄기.kt
  src/main/kotlin/heejik/21week/알파벳.kt
  src/main/kotlin/heejik/22week/ABCDE.kt
  src/main/kotlin/heejik/22week/감시 피하기.kt
  src/main/kotlin/heejik/22week/여왕벌.kt
  src/main/kotlin/heejik/22week/죽음의 게임.kt
  src/main/kotlin/heejik/22week/최소 회의실 개수.kt
  src/main/kotlin/heejik/22week/탑.kt
  src/main/kotlin/heejik/22week/평범한 배낭.kt
Labels: 희직

#97 [전현수] - 로봇 청소기, 보물섬, 센서, 합분해
  src/main/kotlin/hyunsoo/23week/로봇 청소기.kt
  src/main/kotlin/hyunsoo/23week/보물섬.kt
  src/main/kotlin/hyunsoo/23week/센서.kt
  src/main/kotlin/hyunsoo/23week/합분해.kt
Labels: 현수

#99 [소병희] 센서, 로봇 청소기, 합분해, 보물섬
  src/main/kotlin/byeonghee/23week/로봇 청소기.kt
  src/main/kotlin/byeonghee/23week/보물섬.kt
  src/main/kotlin/byeonghee/23week/센서.kt
  src/main/kotlin/byeonghee/23week/합분해.kt
Labels: 병희

#100 [이지민] 로봇 청소기, 보물섬, 센서, 합분해
  src/main/kotlin/jimin/23week/로봇 청소기.kt
  src/main/kotlin/jimin/23week/보물섬.kt
  src/main/kotlin/jimin/23week/센서.kt
  src/main/kotlin/jimin/23week/합분해.kt
Labels: 지민

#98 [장희직] - 로봇 청소기, 보물섬, 센서, 합분해
  src/main/kotlin/heejik/23week/로봇 청소기.kt
  src/main/kotlin/heejik/23week/보물섬.kt
  src/main/kotlin/heejik/23week/센서.kt
  src/main/kotlin/heejik/23week/합분해.kt
Labels: 희직

#104 [전현수] - 트리와 쿼리, 도서관, 좋은 수열
  src/main/kotlin/hyunsoo/24week/도서관.kt
  src/main/kotlin/hyunsoo/24week/좋은 수열.kt
  src/main/kotlin/hyunsoo/24week/트리와 쿼리.kt
Labels: 현수

#105 [장희직] 도서관, 좋은수열, 쿼리와 트리, 행렬 테두리 회전하기
  src/main/kotlin/heejik/24week/도서관.kt
  src/main/kotlin/heejik/24week/좋은수열.kt
  src/main/kotlin/heejik/24week/트리와 쿼리.kt
  src/main/kotlin/heejik/24week/행렬 테두리 회전하기.kt
Labels: 희직

#103 [이지민] 도서관, 좋은수열, 쿼리와 트리, 행렬 테두리 회전하기
  src/main/kotlin/jimin/24week/도서관.kt
  src/main/kotlin/jimin/24week/좋은수열.kt
  src/main/kotlin/jimin/24week/트리와 쿼리.kt
  src/main/kotlin/jimin/24week/행렬 테두리 회전하기.kt
Labels: 지민

#102 [소병희] 트리와 쿼리, 행렬 테두리 회전하기, 도서관, 좋은수열
  src/main/kotlin/byeonghee/24week/도서관.kt
  src/main/kotlin/byeonghee/24week/좋은수열.kt
  src/main/kotlin/byeonghee/24week/트리와 쿼리.kt
  src/main/kotlin/byeonghee/24week/행렬 테두리 회전하기.kt
Labels: 병희
