Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2023-05, with the labels that each got.

#140 [소병희] 운동, 집합, 이모티콘, 물병
  src/main/kotlin/byeonghee/week33/물병.kt
  src/main/kotlin/byeonghee/week33/운동.kt
  src/main/kotlin/byeonghee/week33/이모티콘.kt
  src/main/kotlin/byeonghee/week33/집합.kt
Labels: 병희

#145 [이지민] - 저울, 연속된 부분 수열의 합, Contact, 행복 유치원
  src/main/kotlin/jimin/34week/Contact.kt
  src/main/kotlin/jimin/34week/연속된 부분 수열의 합.kt
  src/main/kotlin/jimin/34week/저울.kt
  src/main/kotlin/jimin/34week/행복 유치원.kt
Labels: 지민

#144 [소병희] Contact, 행복 유치원, 연속된 부분 수열의 합, 저울
  src/main/kotlin/byeonghee/week34/Contact.kt
  src/main/kotlin/byeonghee/week34/연속된 부분 수열의 합.kt
  src/main/kotlin/byeonghee/week34/저울.kt
  src/main/kotlin/byeonghee/week34/행복 유치원.kt
Labels: 병희

#142 [장희직] - 연속된 부분 수열의 합, Contact, 행복 유치원, 저울
  src/main/kotlin/heejik/34week/Contact.kt
  src/main/kotlin/heejik/34week/연속된 부분 수열의 합.kt
  src/main/kotlin/heejik/34week/저울.kt
  src/main/kotlin/heejik/34week/행복 유치원.kt
Labels: 희직
