Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2023-04, with the labels that each got.

#129 [장희직] 안녕, 컨베이어 벨트 위의 로봇, 빙산, 상어 초등학교
  src/main/kotlin/heejik/29week/빙산.kt
  src/main/kotlin/heejik/29week/상어 초등학교.kt
  src/main/kotlin/heejik/29week/안녕.kt
  src/main/kotlin/heejik/29week/컨베이어 벨트 위의 로봇.kt
Labels: 희직

#128 [이지민] 안녕, 컨베이어 벨트 위의 로봇, 빙산, 상어 초등학교
  src/main/kotlin/jimin/28week/연구소.kt
  src/main/kotlin/jimin/28week/친구비.kt
  src/main/kotlin/jimin/29week/빙산.kt
  src/main/kotlin/jimin/29week/상어 초등학교.kt
  src/main/kotlin/jimin/29week/안녕.kt
  src/main/kotlin/jimin/29week/컨베이어 벨트 위의 로봇.kt
Labels: 지민

#130 [소병희] 컨베이어 벨트 위의 로봇, 빙산, 상어초등학교, 안녕
  src/main/kotlin/byeonghee/week29/빙산.kt
  src/main/kotlin/byeonghee/week29/상어 초등학교.kt
  src/main/kotlin/byeonghee/week29/안녕.kt
  src/main/kotlin/byeonghee/week29/컨베이어벨트위의로봇.kt
Labels: 병희

#127 [전현수] - 빙산, 컨베이어 벨트 위의 로봇, 안녕, 상어 초등학교
  src/main/kotlin/hyunsoo/29week/빙산.kt
  src/main/kotlin/hyunsoo/29week/상어 초등학교.kt
  src/main/kotlin/hyunsoo/29week/안녕.kt
  src/main/kotlin/hyunsoo/29week/컨베이어 벨트 위의 로봇.kt
Labels: 현수

#135 [이지민] - 테트로미노, 마법사 상어와 비바라기, 과제
  src/main/kotlin/jimin/29week/빙산.kt
  src/main/kotlin/jimin/30week/과제.py
  src/main/kotlin/jimin/30week/마법사 상어와 비바라기.py
  src/main/kotlin/jimin/30week/테트로미노.py
Labels: 지민

#132 [전현수] - 경로 찾기, 마법사 상어와 비바라기, 과제, 테트로미노
  src/main/kotlin/hyunsoo/30week/경로 찾기.kt
  src/main/kotlin/hyunsoo/30week/과제.kt
  src/main/kotlin/hyunsoo/30week/마법사 상어와 비바라기.kt
  src/main/kotlin/hyunsoo/30week/테트로미노.kt
Labels: 현수

#134 [소병희] 경로 찾기, 테트로미노, 마법사 상어와 비바라기, 과제
  src/main/kotlin/byeonghee/week30/경로 찾기.kt
  src/main/kotlin/byeonghee/week30/과제.kt
  src/main/kotlin/byeonghee/week30/마법사상어와비바라기.kt
  src/main/kotlin/byeonghee/week30/테트로미노.kt
Labels: 병희

#133 [장희직] - 경로 찾기, 마법사 상어와 비바라기, 과제, 테트로미노
  src/main/kotlin/heejik/30week/경로 찾기.kt
  src/main/kotlin/heejik/30week/과제.kt
  src/main/kotlin/heejik/30week/마법사 상어와 비바라기.kt
  src/main/kotlin/heejik/30week/테트로미노.kt
Labels: 희직

#139 [장희직] - 운동, 물병, 이모티콘, 집합
  src/main/kotlin/heejik/30week/과제.kt
  src/main/kotlin/heejik/31week/램프.kt
  src/main/kotlin/heejik/31week/물병.kt
  src/main/kotlin/heejik/31week/물통.kt
  src/main/kotlin/heejik/31week/빗물.kt
  src/main/kotlin/heejik/31week/사과나무.kt
  src/main/kotlin/heejik/31week/숫자고르기.kt
  src/main/kotlin/heejik/31week/신입 사원.kt
  src/main/kotlin/heejik/31week/암호 만들기.kt
  src/main/kotlin/heejik/31week/운동.kt
  src/main/kotlin/heejik/31week/이모티콘.kt
  src/main/kotlin/heejik/31week/인구이동.kt
  src/main/kotlin/heejik/31week/전깃줄.kt
  src/main/kotlin/heejik/31week/집합.kt
  src/main/kotlin/heejik/31week/토마토.kt
  src/main/kotlin/heejik/31week/파이프 옮기기 1.kt
  src/main/kotlin/heejik/31week/포도주 시식.kt
  src/main/kotlin/jimin/27week/팰린드롬.kt
Labels: 희직

#138 [이지민] - 집합, 이모티콘, 물병, 운동
  src/main/kotlin/jimin/30week/과제.py
  src/main/kotlin/jimin/31week/물병.kt
  src/main/kotlin/jimin/31week/운동.kt
  src/main/kotlin/jimin/31week/이모티콘.kt
  src/main/kotlin/jimin/31week/집합.kt
Labels: 지민
