Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2023-10, with the labels that each got.

#178 [소병희] 게임, 연산자 끼워넣기, A와 B
  src/main/kotlin/byeonghee/week45/A와 B.kt
  src/main/kotlin/byeonghee/week45/게임.kt
  src/main/kotlin/byeonghee/week45/연산자 끼워넣기.kt
Labels: 병희

#182 [이지민] - 농장 관리, 빌런 호석, 숨박꼭질 3, 경주로 건설
  src/main/kotlin/jimin/46week/경주로 건설.py
  src/main/kotlin/jimin/46week/농장 관리.py
  src/main/kotlin/jimin/46week/빌런 호석.py
  src/main/kotlin/jimin/46week/숨박꼭질 3.py
Labels: 지민

#183 [장희직] - 숨바꼭질 3, 농장 관리, 빌런 호석
  src/main/kotlin/heejik/46week/농장 관리.kt
  src/main/kotlin/heejik/46week/빌런 호석.kt
  src/main/kotlin/heejik/46week/숨바꼭질 3.kt
Labels: 희직

#186 [전현수] - 알고스팟, A와 B 2, 입국심사, 회장뽑기
  src/main/kotlin/hyunsoo/47week/A와 B 2.kt
  src/main/kotlin/hyunsoo/47week/알고스팟.kt
  src/main/kotlin/hyunsoo/47week/입국심사.kt
  src/main/kotlin/hyunsoo/47week/회장뽑기.kt
Labels: 현수

#188 [소병희] 알고스팟, A와 B 2, 회장뽑기, 입국심사
  src/main/kotlin/byeonghee/week47/A와 B 2.kt
  src/main/kotlin/byeonghee/week47/알고스팟.kt
  src/main/kotlin/byeonghee/week47/입국심사.kt
  src/main/kotlin/byeonghee/week47/회장뽑기.kt
Labels: 병희

#189 [이지민] - A와 B 2, 알고스팟, 회장뽑기, 입국심사
  src/main/kotlin/jimin/47week/A와 B 2.py
  src/main/kotlin/jimin/47week/알고스팟.py
  src/main/kotlin/jimin/47week/입국심사.py
  src/main/kotlin/jimin/47week/회장뽑기.py
Labels: 지민

#193 [이지민] - 주차장, 순위, 백도어
  src/main/kotlin/jimin/48week/백도어.py
  src/main/kotlin/jimin/48week/순위.py
  src/main/kotlin/jimin/48week/주차장.py
Labels: 지민

#194 [장희직] - 주차장, 순위, 탑
  src/main/kotlin/heejik/48week/백도어.kt
  src/main/kotlin/heejik/48week/순위.kt
  src/main/kotlin/heejik/48week/주차장.kt
  src/main/kotlin/heejik/48week/탑.kt
Labels: 희직

#191 [전현수] - 백도어, 주차장, 순위, 탑
  src/main/kotlin/hyunsoo/48week/백도어.kt
  src/main/kotlin/hyunsoo/48week/순위.kt
  src/main/kotlin/hyunsoo/48week/주차장.kt
  src/main/kotlin/hyunsoo/48week/탑.kt
Labels: 지민, 현수, 병희, 희직

#192 [소병희] 백도어, 탑, 주차장
  src/main/kotlin/byeonghee/week48/백도어.kt
  src/main/kotlin/byeonghee/week48/주차장.kt
  src/main/kotlin/byeonghee/week48/탑.kt
Labels: 병희
