Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2023-11, with the labels that each got.

#197 [이지민] - 노드사이의 거리, 벼락차기, 빗물, 할인 행사
  src/main/kotlin/jimin/49week/노드사이의 거리.py
  src/main/kotlin/jimin/49week/벼락치기.py
  src/main/kotlin/jimin/49week/빗물.py
  src/main/kotlin/jimin/49week/할인 행사.py
Labels: 지민

#199 [장희직] - 노드사이의 거리, 빗물, 벼락치기, 할인 행사
  src/main/kotlin/heejik/48week/백도어.kt
  src/main/kotlin/heejik/49week/노드사이의 거리.kt
  src/main/kotlin/heejik/49week/벼락치기.kt
  src/main/kotlin/heejik/49week/빗물.kt
  src/main/kotlin/heejik/49week/할인 행사.kt
Labels: 희직

#198 [전현수] - 노드사이의 거리, 빗물, 벼락치기, 할인 행사
  src/main/kotlin/hyunsoo/49week/노드사이의 거리.kt
  src/main/kotlin/hyunsoo/49week/벼락치기.kt
  src/main/kotlin/hyunsoo/49week/빗물.kt
  src/main/kotlin/hyunsoo/49week/할인 행사.kt
Labels: 현수

#205 [소병희] - 숫자고르기, 북쪽나라의 도로, 두 큐 합 같게 만들기
  src/main/kotlin/byeonghee/week49/노드사이의 거리.kt
  src/main/kotlin/byeonghee/week49/벼락치기.kt
  src/main/kotlin/byeonghee/week49/빗물.kt
  src/main/kotlin/byeonghee/week49/할인 행사.kt
  src/main/kotlin/byeonghee/week50/두 큐 합 같게 만들기.kt
  src/main/kotlin/byeonghee/week50/북쪽나라의 도로.kt
  src/main/kotlin/byeonghee/week50/숫자고르기.kt
  src/main/kotlin/byeonghee/week50/연구소2.kt
Labels: 병희

#202 [전현수] - 연구소 2, 두 큐 합 같게 만들기, 숫자고르기, 북쪽나라의 도로
  src/main/kotlin/hyunsoo/50week/두 큐 합 같게 만들기.kt
  src/main/kotlin/hyunsoo/50week/북쪽나라의 도로.kt
  src/main/kotlin/hyunsoo/50week/숫자고르기.kt
  src/main/kotlin/hyunsoo/50week/연구소 2.kt
Labels: 현수

#203 [장희직] - 연구소 2, 두 큐 합 같게 만들기, 숫자고르기, 북쪽나라의 도로
  src/main/kotlin/heejik/50week/두 큐 합 같게 만들기.kt
  src/main/kotlin/heejik/50week/북쪽나라의 도로.kt
  src/main/kotlin/heejik/50week/숫자고르기.kt
  src/main/kotlin/heejik/50week/연구소 2.kt
Labels: 희직
