Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2023-01, with the labels that each got.

#65 [소병희] 기적의 매매법, DNA, 등수 구하기, 수 이어 쓰기 1
  src/main/kotlin/byeonghee/13week/DNA.kt
  src/main/kotlin/byeonghee/13week/기적의 매매법.kt
  src/main/kotlin/byeonghee/13week/등수 구하기.kt
  src/main/kotlin/byeonghee/13week/수 이어 쓰기 1.kt
Labels: 병희

#62 [전현수] 기적의 매매법, 수 이어 쓰기 1, 등수 구하기, DNA
  src/main/kotlin/hyunsoo/13week/DNA.kt
  src/main/kotlin/hyunsoo/13week/기적의 매매법.kt
  src/main/kotlin/hyunsoo/13week/두 수의 합.kt
  src/main/kotlin/hyunsoo/13week/두 용액.kt
  src/main/kotlin/hyunsoo/13week/등수 구하기.kt
  src/main/kotlin/hyunsoo/13week/배열 합치기.kt
  src/main/kotlin/hyunsoo/13week/부분합.kt
  src/main/kotlin/hyunsoo/13week/소수의 연속합.kt
  src/main/kotlin/hyunsoo/13week/수 이어 쓰기 1.kt
  src/main/kotlin/hyunsoo/13week/수들의 합 2.kt
  src/main/kotlin/hyunsoo/13week/수들의 합 5.kt
  src/main/kotlin/hyunsoo/13week/수열.kt
  src/main/kotlin/hyunsoo/13week/주몽.kt
Labels: 현수

#64 [장희직] 기적의 매매법, 수 이어 쓰기 1, 등수 구하기, DNA
  src/main/kotlin/heejik/12week/안녕.kt
  src/main/kotlin/heejik/12week/트럭.kt
  src/main/kotlin/heejik/13week/DNA.kt
  src/main/kotlin/heejik/13week/등수 구하기.kt
  src/main/kotlin/heejik/13week/수 이어 쓰기 1.kt
  src/main/kotlin/heejik/13week/시계.kt
  src/main/kotlin/heejik/13week/크로스워드.kt
  src/main/kotlin/heejik/13week/🐜 기적의 매매법 🐜.kt
Labels: 희직

#63 [이지민] 기적의 매매법, 수 이어 쓰기 1, 등수 구하기, DNA
  src/main/kotlin/jimin/13week/DNA.kt
  src/main/kotlin/jimin/13week/기적의 매매법.kt
  src/main/kotlin/jimin/13week/등수 구하기.kt
  src/main/kotlin/jimin/13week/수 이어 쓰기1.kt
Labels: 지민

#67 [전현수] 수 고르기, 추월, 트리 순회, 링크와 스타트
  src/main/kotlin/hyunsoo/17week/링크와 스타트.kt
  src/main/kotlin/hyunsoo/17week/수 고르기.kt
  src/main/kotlin/hyunsoo/17week/스택.kt
  src/main/kotlin/hyunsoo/17week/좌표 압축.kt
  src/main/kotlin/hyunsoo/17week/추월.kt
  src/main/kotlin/hyunsoo/17week/트리 순회.kt
Labels: 현수

#68 [소병희] 추월, 수 고르기, 트리 순회, 링크와 스타트
  src/main/kotlin/byeonghee/17week/링크와 스타트.kt
  src/main/kotlin/byeonghee/17week/수 고르기.kt
  src/main/kotlin/byeonghee/17week/추월.kt
  src/main/kotlin/byeonghee/17week/트리 순회.kt
Labels: 병희

#70 [장희직] 추월, 수 고르기, 트리 순회, 링크와 스타트
  src/main/kotlin/heejik/13week/등수 구하기.kt
  src/main/kotlin/heejik/13week/🐜 기적의 매매법 🐜.kt
  src/main/kotlin/heejik/14week/대표 자연수.kt
  src/main/kotlin/heejik/14week/링크와 스타트.kt
  src/main/kotlin/heejik/14week/별 찍기 - 19.kt
  src/main/kotlin/heejik/14week/수 고르기.kt
  src/main/kotlin/heejik/14week/추월.kt
  src/main/kotlin/heejik/14week/트리 순회.kt
Labels: 희직

#69 [이지민] 추월, 수 고르기, 트리 순회, 링크와 스타트
  src/main/kotlin/jimin/17week/링크와 스타트.kt
  src/main/kotlin/jimin/17week/수 고르기.kt
  src/main/kotlin/jimin/17week/추월.kt
  src/main/kotlin/jimin/17week/트리 순회.kt
Labels: 지민

#73 [소병희] Z, 부분수열의 합, 거짓말, 레이저빔은 어디로
  src/main/kotlin/byeonghee/18week/Z.kt
  src/main/kotlin/byeonghee/18week/거짓말.kt
  src/main/kotlin/byeonghee/18week/레이저빔은 어디로.kt
  src/main/kotlin/byeonghee/18week/부분수열의 합.kt
Labels: 병희

#74 [전현수] - 거짓말, 부분수열의 합, 레이저빔은 어디로, Z
  src/main/kotlin/hyunsoo/18week/Z.kt
  src/main/kotlin/hyunsoo/18week/거짓말.kt
  src/main/kotlin/hyunsoo/18week/레이저빔은 어디로.kt
  src/main/kotlin/hyunsoo/18week/부분수열의 합.kt
Labels: 현수

#75 [장희직] Z, 거짓말, 레이저빔은 어디로, 부분수열의 합
  src/main/kotlin/heejik/14week/추월.kt
  src/main/kotlin/heejik/17week/대표 자연수.kt
  src/main/kotlin/heejik/17week/링크와 스타트.kt
  src/main/kotlin/heejik/17week/별 찍기 - 19.kt
  src/main/kotlin/heejik/17week/수 고르기.kt
  src/main/kotlin/heejik/17week/추월.kt
  src/main/kotlin/heejik/17week/트리 순회.kt
  src/main/kotlin/heejik/18week/Z.kt
  src/main/kotlin/heejik/18week/거짓말.kt
  src/main/kotlin/heejik/18week/레이저빔은 어디로.kt
  src/main/kotlin/heejik/18week/부분수열의 합.kt
Labels: 희직

#72 [이지민] Z, 거짓말, 레이저빔은 어디로, 부분수열의 합
  src/main/kotlin/heejik/13week/DNA.kt
  src/main/kotlin/hyunsoo/13week/DNA.kt
  src/main/kotlin/jimin/17week/수 고르기.kt
  src/main/kotlin/jimin/18week/Z.kt
  src/main/kotlin/jimin/18week/거짓말.kt
  src/main/kotlin/jimin/18week/동전 0.kt
  src/main/kotlin/jimin/18week/레이저빔은 어디로.kt
  src/main/kotlin/jimin/18week/부분수열의 합.kt
Labels: 지민

#80 [소병희] 단지번호붙이기, 동전 1, 2xn 타일링, 숨바꼭질
  src/main/kotlin/byeonghee/19week/2xn 타일링.kt
  src/main/kotlin/byeonghee/19week/단지번호붙이기.kt
  src/main/kotlin/byeonghee/19week/동전1.kt
  src/main/kotlin/byeonghee/19week/숨바꼭질.kt
Labels: 병희

#77 [전현수] - 단지번호붙이기, 2xn 타일링, 동전 1, 숨바꼭질
  src/main/kotlin/hyunsoo/19week/2xn 타일링.kt
  src/main/kotlin/hyunsoo/19week/단지번호붙이기.kt
  src/main/kotlin/hyunsoo/19week/동전 1.kt
  src/main/kotlin/hyunsoo/19week/숨바꼭질.kt
  src/main/kotlin/hyunsoo/19week/적록색약.kt
  src/main/kotlin/hyunsoo/19week/통계학.kt
  src/main/kotlin/hyunsoo/19week/평범한 배낭.kt
  src/main/kotlin/hyunsoo/19week/피보나치 함수.kt
  src/main/kotlin/hyunsoo/template.kt
Labels: 현수

#79 [장희직] - 단지번호붙이기, 2xn 타일링, 동전 1, 숨바꼭질
  src/main/kotlin/heejik/19week/2×n 타일링.kt
  src/main/kotlin/heejik/19week/단지번호붙이기.kt
  src/main/kotlin/heejik/19week/동전 1.kt
  src/main/kotlin/heejik/19week/숨바꼭질.kt
  src/main/kotlin/heejik/19week/치킨 배달.kt
  src/main/kotlin/heejik/19week/홀수 홀릭 호석.kt
Labels: 희직

#83 [이지민] - 양, 별자리 만들기, 안전구역, 에너지 모으기
  src/main/kotlin/jimin/19week/날짜 계산.kt
  src/main/kotlin/jimin/19week/리모컨.kt
  src/main/kotlin/jimin/20week/별자리 만들기.kt
  src/main/kotlin/jimin/20week/안전 영역.kt
  src/main/kotlin/jimin/20week/양.kt
  src/main/kotlin/jimin/20week/에너지 모으기.kt
Labels: 지민

#85 [소병희] 양, 별자리 만들기, 에너지 모으기, 안전 영역
  src/main/kotlin/byeonghee/20week/별자리 만들기.kt
  src/main/kotlin/byeonghee/20week/안전 영역.kt
  src/main/kotlin/byeonghee/20week/양.kt
  src/main/kotlin/byeonghee/20week/에너지 모으기.kt
Labels: 병희

#82 [전현수] - 양, 별자리 만들기, 안전구역, 에너지 모으기
  src/main/kotlin/hyunsoo/20week/별자리_만들기.kt
  src/main/kotlin/hyunsoo/20week/안전 영역.kt
  src/main/kotlin/hyunsoo/20week/양.kt
  src/main/kotlin/hyunsoo/20week/에너지 모으기.kt
  src/main/kotlin/hyunsoo/20week/최소 스패닝 트리.kt
  src/main/kotlin/hyunsoo/20week/최소비용_구하기.kt
  src/main/kotlin/hyunsoo/20week/택배 배송.kt
Labels: 현수

#84 [장희직] - 양, 별자리 만들기, 안전구역, 에너지 모으기
  src/main/kotlin/heejik/20week/별자리 만들기.kt
  src/main/kotlin/heejik/20week/안전 영역.kt
  src/main/kotlin/heejik/20week/양.kt
  src/main/kotlin/heejik/20week/에너지 모으기.kt
Labels: 희직
