Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2023-06, with the labels that each got.

#149 [이지민] - 토마토, 인구 이동, 카드 정렬하기
  src/main/kotlin/jimin/35week/인구 이동.kt
  src/main/kotlin/jimin/35week/카드 정렬하기.kt
  src/main/kotlin/jimin/35week/토마토.kt
Labels: 지민

#148 [전현수] - 인구 이동, 카드 정렬하기, 토마토, RGB거리 2
  src/main/kotlin/hyunsoo/38week/RGB거리 2.kt
  src/main/kotlin/hyunsoo/38week/인구 이동.kt
  src/main/kotlin/hyunsoo/38week/카드 정렬하기.kt
  src/main/kotlin/hyunsoo/38week/토마토.kt
Labels: 현수

#147 [장희직] - 인구 이동, RGB거리 2, 토마토, 카드 정렬하기
  src/main/kotlin/heejik/34week/연속된 부분 수열의 합.kt
  src/main/kotlin/heejik/35week/Puyo Puyo.kt
  src/main/kotlin/heejik/35week/RGB거리 2.kt
  src/main/kotlin/heejik/35week/가장 큰 정사각형.kt
  src/main/kotlin/heejik/35week/단어 수학.kt
  src/main/kotlin/heejik/35week/인구 이동.kt
  src/main/kotlin/heejik/35week/장군.kt
  src/main/kotlin/heejik/35week/카드 정렬하기.kt
  src/main/kotlin/heejik/35week/토마토.kt
Labels: 희직

#150 [소병희] 카드 정렬하기, 토마토, RGB거리 2
  src/main/kotlin/byeonghee/week38/RGB거리 2.kt
  src/main/kotlin/byeonghee/week38/카드 정렬하기.kt
  src/main/kotlin/byeonghee/week38/토마토.kt
Labels: 병희

#153 [전현수] - 오목, 봄버맨, 자유 이용권, 줄세우기
  src/main/kotlin/hyunsoo/39week/봄버맨.kt
  src/main/kotlin/hyunsoo/39week/오목.kt
  src/main/kotlin/hyunsoo/39week/자유 이용권.kt
  src/main/kotlin/hyunsoo/39week/줄세우기.kt
Labels: 현수

#154 [장희직] - 오목, 봄버맨, 자유 이용권, 줄세우기
  src/main/kotlin/heejik/36week/봄버맨.kt
  src/main/kotlin/heejik/36week/오목.kt
  src/main/kotlin/heejik/36week/자유 이용권.kt
  src/main/kotlin/heejik/36week/줄세우기.kt
Labels: 희직

#152 [소병희] 오목, 줄세우기, 봄버맨, 자유이용권
  src/main/kotlin/byeonghee/week39/봄버맨.kt
  src/main/kotlin/byeonghee/week39/오목.kt
  src/main/kotlin/byeonghee/week39/자유이용권.kt
  src/main/kotlin/byeonghee/week39/줄세우기.kt
Labels: 병희

#156 [전현수] - 지름길, 로봇 시뮬레이션, 개미의 이동, 트리
  .idea/misc.xml
  src/main/kotlin/hyunsoo/39week/줄세우기.kt
  src/main/kotlin/hyunsoo/41week/개미의 이동.kt
  src/main/kotlin/hyunsoo/41week/로봇 시뮬레이션.kt
  src/main/kotlin/hyunsoo/41week/지름길.kt
  src/main/kotlin/hyunsoo/41week/트리.kt
Labels: 현수

#157 [이지민] 지름길, 개미의 이동, 트리, 로봇 시뮬레이션
  src/main/kotlin/jimin/36week/봄버맨.kt
  src/main/kotlin/jimin/36week/오목.kt
  src/main/kotlin/jimin/36week/자유 이용권.kt
  src/main/kotlin/jimin/41week/개미의 이동.kt
  src/main/kotlin/jimin/41week/로봇 시뮬레이션.kt
  src/main/kotlin/jimin/41week/지름길.kt
  src/main/kotlin/jimin/41week/트리.kt
Labels: 지민

#158 [장희직] 지름길, 개미의 이동, 트리, 로봇 시뮬레이션
  src/main/kotlin/heejik/40week/개미의 이동.kt
  src/main/kotlin/heejik/40week/로봇 시뮬레이션.kt
  src/main/kotlin/heejik/40week/지름길.kt
  src/main/kotlin/heejik/40week/트리.kt
Labels: 희직
