Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2023-08, with the labels that each got.

#159 [소병희] 트리, 지름길, 개미의 이동, 로봇 시뮬레이션
  src/main/kotlin/byeonghee/week41/개미의 이동.kt
  src/main/kotlin/byeonghee/week41/로봇 시뮬레이션.kt
  src/main/kotlin/byeonghee/week41/지름길.kt
  src/main/kotlin/byeonghee/week41/트리.kt
Labels: 병희

#162 [전현수] - 로또, 이동하기, 바이러스, 블로그
  src/main/kotlin/hyunsoo/42week/1, 2, 3 더하기 3.kt
  src/main/kotlin/hyunsoo/42week/30.kt
  src/main/kotlin/hyunsoo/42week/로또.kt
  src/main/kotlin/hyunsoo/42week/바이러스.kt
  src/main/kotlin/hyunsoo/42week/블로그.kt
  src/main/kotlin/hyunsoo/42week/연속합.kt
  src/main/kotlin/hyunsoo/42week/이동하기.kt
Labels: 현수

#164 [장희직] 로또, 바이러스, 이동하기, 블로그
  src/main/kotlin/heejik/41week/개미의 이동.kt
  src/main/kotlin/heejik/41week/로봇 시뮬레이션.kt
  src/main/kotlin/heejik/41week/지름길.kt
  src/main/kotlin/heejik/41week/트리.kt
  src/main/kotlin/heejik/42week/로또.kt
  src/main/kotlin/heejik/42week/바이러스.kt
  src/main/kotlin/heejik/42week/블로그.kt
  src/main/kotlin/heejik/42week/이동하기.kt
Labels: 희직

#161 [이지민] 로또, 바이러스, 블로그, 이동하기
  src/main/kotlin/jimin/42week/로또.kt
  src/main/kotlin/jimin/42week/바이러스.kt
  src/main/kotlin/jimin/42week/블로그.kt
  src/main/kotlin/jimin/42week/이동하기.kt
Labels: 지민
