Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2024-04, with the labels that each got.

#232 [소병희] 나의 인생에는 수학과 함께, 이차원 배열과 연산
  src/main/kotlin/byeonghee/week56/나의 인생에는 수학과 함께.kt
  src/main/kotlin/byeonghee/week56/루돌프의 반란.kt
  src/main/kotlin/byeonghee/week56/이차원 배열과 연산.kt
  src/main/kotlin/byeonghee/week56/톱니바퀴2.kt
Labels: 병희

#238 [장희직] - 왕실의 기사 대결, 메이즈 러너, 귤 고르기, 아이템 줍기
  src/main/kotlin/heejik/57week/귤 고르기.py
  src/main/kotlin/heejik/57week/메이즈 러너.py
  src/main/kotlin/heejik/57week/아이템 줍기.py
  src/main/kotlin/heejik/57week/왕실의 기사 대결.py
Labels: 희직

#237 [소병희] - 귤 고르기
  src/main/kotlin/byeonghee/week57/귤 고르기.kt
  src/main/kotlin/byeonghee/week57/아이템 줍기.java
Labels: 병희

#236 [이지민] - 왕실의 기사 대결, 메이즈 러너, 귤 고르기
  src/main/kotlin/jimin/57week/귤고르기.py
  src/main/kotlin/jimin/57week/메이즈 러너.py
  src/main/kotlin/jimin/57week/왕실의 기사 대결.py
Labels: 지민

#241 [이지민] - 술래잡기, 양치기 꿍, 포탑 부수기
  src/main/kotlin/jimin/58week/술래잡기.py
  src/main/kotlin/jimin/58week/양치기 꿍.py
  src/main/kotlin/jimin/58week/포탑 부수기.py
Labels: 지민

#242 [소병희] - 양치기 꿍, 포탑 부수기, 토끼와 경주
  src/main/kotlin/byeonghee/week57/아이템 줍기.java
  src/main/kotlin/byeonghee/week58/BYEONGHEE_BJ_3187.java
  src/main/kotlin/byeonghee/week58/BYEONGHEE_CODETREE_DESTROY_THE_TURRET.java
  src/main/kotlin/byeonghee/week58/토끼와 경주.kt
Labels: 병희

#243 [장희직] - 양치기 꿍, 포탑 부수기, 토끼와 경주, 술래잡기
  src/main/kotlin/heejik/58week/고대 문명 유적 탐사.py
  src/main/kotlin/heejik/58week/괄호의 값.kt
  src/main/kotlin/heejik/58week/꼬리잡기 놀이.py
  src/main/kotlin/heejik/58week/나무박멸.py
  src/main/kotlin/heejik/58week/달팽이 숫자.py
  src/main/kotlin/heejik/58week/드래곤 앤 던전.kt
  src/main/kotlin/heejik/58week/백만 장자 프로젝트.py
  src/main/kotlin/heejik/58week/술래잡.py
  src/main/kotlin/heejik/58week/싸움땅.py
  src/main/kotlin/heejik/58week/양치기 꿍.py
  src/main/kotlin/heejik/58week/예술성.py
  src/main/kotlin/heejik/58week/정육면체 한번 더 굴리기.py
  src/main/kotlin/heejik/58week/포탑 부수기.py
  src/main/kotlin/heejik/59week/동전.kt
  src/main/kotlin/heejik/59week/멀쩡한 사격형.kt
  src/main/kotlin/heejik/59week/호텔.kt
Labels: 희직

#245 [장희직] - 동전, 멀쩡한 사각형, 호텔
  src/main/kotlin/heejik/58week/고대 문명 유적 탐사.py
  src/main/kotlin/heejik/58week/괄호의 값.kt
  src/main/kotlin/heejik/58week/꼬리잡기 놀이.py
  src/main/kotlin/heejik/58week/나무박멸.py
  src/main/kotlin/heejik/58week/달팽이 숫자.py
  src/main/kotlin/heejik/58week/드래곤 앤 던전.kt
  src/main/kotlin/heejik/58week/백만 장자 프로젝트.py
  src/main/kotlin/heejik/58week/술래잡.py
  src/main/kotlin/heejik/58week/싸움땅.py
  src/main/kotlin/heejik/58week/양치기 꿍.py
  src/main/kotlin/heejik/58week/예술성.py
  src/main/kotlin/heejik/58week/정육면체 한번 더 굴리기.py
  src/main/kotlin/heejik/58week/포탑 부수기.py
  src/main/kotlin/heejik/59week/동전.kt
  src/main/kotlin/heejik/59week/멀쩡한 사격형.kt
  src/main/kotlin/heejik/59week/호텔.kt
Labels: 희직

#247 [소병희] - 동전, 호텔, 멀쩡한 사각형, 택배 배송
  src/main/kotlin/byeonghee/week59/동전.kt
  src/main/kotlin/byeonghee/week59/멀쩡한 사각형.kt
  src/main/kotlin/byeonghee/week59/택배 배송.kt
  src/main/kotlin/byeonghee/week59/호텔.kt
Labels: 병희

#249 [장희직] - 트리의 지름, 공유기 설치
  src/main/kotlin/heejik/60week/공유기 설치.kt
  src/main/kotlin/heejik/60week/뮤탈리스크.kt
  src/main/kotlin/heejik/60week/스티커 재배치.kt
  src/main/kotlin/heejik/60week/트리의 지름.kt
Labels: 희직

#251 [이지민] - 공유기 설치, 트리의 지름, 뮤탈리스트
  src/main/kotlin/jimin/60week/공유기 설치.kt
  src/main/kotlin/jimin/60week/뮤탈리스트.kt
  src/main/kotlin/jimin/60week/트리의 지름.kt
Labels: 지민
