Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2024-03, with the labels that each got.

#213 [장희직] - N번째 큰 수, 종이의 개수, 택배 배달과 수거하기, 222-폴링
  src/main/kotlin/heejik/52week/222-폴링.kt
  src/main/kotlin/heejik/52week/N번째 큰 수.kt
  src/main/kotlin/heejik/52week/도넛과 막대 그래프.kt
  src/main/kotlin/heejik/52week/도넛과 막대 그래프2.kt
  src/main/kotlin/heejik/52week/종이의 개수.kt
  src/main/kotlin/heejik/52week/택배 배달과 수거하기.kt
Labels: 희직

#212 [이지민] - 222-풀링, 종이의 개수, N번째 큰 수, 택배 배달과 수거하기
  src/main/kotlin/jimin/week52/N번째_큰_수.java
  src/main/kotlin/jimin/week52/종이의 개수.kt
  src/main/kotlin/jimin/week52/택배_배달과_수거하기.java
  src/main/kotlin/jimin/week52/풀링.java
Labels: 지민

#211 [전현수] - N번째 큰 수, 종이의 개수, 222-폴링
  src/main/kotlin/hyunsoo/52week/222-풀링.kt
  src/main/kotlin/hyunsoo/52week/N번째 큰 수.kt
  src/main/kotlin/hyunsoo/52week/종이의 개수.kt
  src/main/kotlin/hyunsoo/52week/택배 배달과 수거하기.kt
Labels: 현수

#217 [이지민] - 구간 합 구하기 5, 작업, 도넛과 막대 그래프
  src/main/kotlin/jimin/53week/구간 합 구하기 5.py
  src/main/kotlin/jimin/53week/도넛과 막대 그래프.py
  src/main/kotlin/jimin/53week/작업.py
  src/main/kotlin/jimin/53week/키 순서.py
Labels: 지민

#219 [장희직] - 작업, 키 순서, 구간 합 구하기 5, 도넛과 막대 그래프
  src/main/kotlin/heejik/53week/구간 합 구하기 5.kt
  src/main/kotlin/heejik/53week/서강그라운드.kt
  src/main/kotlin/heejik/53week/작업.kt
  src/main/kotlin/heejik/53week/키 순서.kt
Labels: 희직

#218 [소병희] - 작업, 키 순서, 구간 합 구하기 5, 도넛과 막대 그래프
  src/main/kotlin/byeonghee/week53/구간 합 구하기 5.kt
  src/main/kotlin/byeonghee/week53/도넛과 막대 그래프.kt
  src/main/kotlin/byeonghee/week53/작업.kt
  src/main/kotlin/byeonghee/week53/키 순서.kt
Labels: 병희

#224 [이지민] - 항체 인식, 토마토, 우체국, 문자열 게임 2
  src/main/kotlin/jimin/54week/문자열 게임 2.py
  src/main/kotlin/jimin/54week/우체국.py
  src/main/kotlin/jimin/54week/토마토.py
  src/main/kotlin/jimin/54week/항체 인식.py
Labels: 지민

#223 [장희직] - 항체 인식, 토마토, 우체국, 문자열 게임 2
  src/main/kotlin/heejik/54week/꿀 따기.kt
  src/main/kotlin/heejik/54week/문자열 게임 2.kt
  src/main/kotlin/heejik/54week/스카이라인 쉬운거.kt
  src/main/kotlin/heejik/54week/우체국.kt
  src/main/kotlin/heejik/54week/토마토.kt
  src/main/kotlin/heejik/54week/항체 인식.kt
Labels: 희직

#221 [전현수] - 항체 인식, 토마토, 우체국, 문자열 게임2
  src/main/kotlin/hyunsoo/54week/문자열 게임 2.kt
  src/main/kotlin/hyunsoo/54week/우체국.kt
  src/main/kotlin/hyunsoo/54week/토마토.kt
  src/main/kotlin/hyunsoo/54week/항체 인식.kt
Labels: 현수

#222 [소병희] - 항체 인식, 토마토, 우체국, 문자열 게임 2
  src/main/kotlin/byeonghee/week54/DFS와 BFS.kt
  src/main/kotlin/byeonghee/week54/문자열 게임 2.kt
  src/main/kotlin/byeonghee/week54/스택 수열.kt
  src/main/kotlin/byeonghee/week54/우체국.kt
  src/main/kotlin/byeonghee/week54/토마토.kt
  src/main/kotlin/byeonghee/week54/항체 인식.kt
Labels: 병희

#226 [전현수] - 보이저 1호, 여행 가자, 꿀 따기, 피로도, 세탁소 사장 동혁, 컵홀더 , 짐 챙기는 숌
  src/main/kotlin/hyunsoo/55week/꿀 따기.kt
  src/main/kotlin/hyunsoo/55week/보이저 1호.kt
  src/main/kotlin/hyunsoo/55week/세탁소 사장 동혁.kt
  src/main/kotlin/hyunsoo/55week/여행 가자.kt
  src/main/kotlin/hyunsoo/55week/짐 챙기는 숌.kt
  src/main/kotlin/hyunsoo/55week/컵홀더.kt
  src/main/kotlin/hyunsoo/55week/피로도.kt
Labels: 현수

#227 [이지민] - 꿀 따기, 여행 가자, 피로도, 보이저 1호
  src/main/kotlin/jimin/55week/꿀 따기.py
  src/main/kotlin/jimin/55week/보이저 1호.py
  src/main/kotlin/jimin/55week/여행 가자.py
  src/main/kotlin/jimin/55week/피로도.py
Labels: 지민

#229 [장희직] - 꿀 따기, 여행 가자, 피로도, 보이저 1호
  src/main/kotlin/heejik/54week/꿀 따기.kt
  src/main/kotlin/heejik/54week/항체 인식.kt
  src/main/kotlin/heejik/55week/N으로 표현.kt
  src/main/kotlin/heejik/55week/가장 먼 노드.kt
  src/main/kotlin/heejik/55week/단어 변환.kt
  src/main/kotlin/heejik/55week/베스트 앨범.kt
  src/main/kotlin/heejik/55week/보이저 1호.kt
  src/main/kotlin/heejik/55week/사다리 조작.kt
  src/main/kotlin/heejik/55week/섬 연결하기.kt
  src/main/kotlin/heejik/55week/여행 가자.kt
  src/main/kotlin/heejik/55week/여행 경로.kt
  src/main/kotlin/heejik/55week/전력망을 둘로 나누기.kt
  src/main/kotlin/heejik/55week/최단경로.kt
  src/main/kotlin/heejik/55week/피로도.kt
Labels: 희직

#228 [소병희] - 보이저 1호, 여행 가자, 꿀 따기, 피로도
  src/main/kotlin/byeonghee/week55/꿀 따기.kt
  src/main/kotlin/byeonghee/week55/보이저 1호.kt
  src/main/kotlin/byeonghee/week55/여행 가자.kt
  src/main/kotlin/byeonghee/week55/피로도.kt
Labels: 병희

#231 [장희직] - 나의 인생에는 수학과 함께, 루돌프의 반란, 톱니바퀴 (2), 이차원 배열과 연산
  src/main/kotlin/heejik/55week/최단경로.kt
  src/main/kotlin/heejik/56week/나의 인생에는 수학과 함께.kt
  src/main/kotlin/heejik/56week/루돌프의 반란.py
  src/main/kotlin/heejik/56week/이차원 배열과 연산.py
  src/main/kotlin/heejik/56week/톱니바퀴(2).py
Labels: 희직

#233 [이지민] - 나의 인생에는 수학과 함께, 톱니바퀴(2), 이차원 배열과 연산, 루돌프의 반란
  src/main/kotlin/jimin/56week/나의 인생에는 수학과 함께.py
  src/main/kotlin/jimin/56week/루돌프의 반란.py
  src/main/kotlin/jimin/56week/이차원 배열과 연산.py
  src/main/kotlin/jimin/56week/톱니바퀴 (2).py
Labels: 지민
