Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2024-05, with the labels that each got.

#250 [소병희] 공유기 설치, 트리의 지름, 뮤탈리스크
  src/main/kotlin/byeonghee/week60/공유기 설치.kt
  src/main/kotlin/byeonghee/week60/뮤탈리스크.kt
  src/main/kotlin/byeonghee/week60/트리의 지름.kt
Labels: 병희

#255 [전현수] - 무인도 여행, 파일 합치기 3, 도넛 행성
  src/main/kotlin/hyunsoo/61week/도넛 행성.kt
  src/main/kotlin/hyunsoo/61week/무인도 여행.kt
  src/main/kotlin/hyunsoo/61week/파일 합치기 3.kt
Labels: 현수

#240 [전현수] - 양치기 꿍, 술래 잡기
  src/main/kotlin/hyunsoo/58week/술래 잡기.kt
  src/main/kotlin/hyunsoo/58week/양치기 꿍.kt
  src/main/kotlin/hyunsoo/58week/토끼와 경주.kt
  src/main/kotlin/hyunsoo/58week/포탑 부수기.kt
Labels: 현수

#253 [소병희] 무인도 여행, 파일 합치기, 도넛 행성, 하노이 탑
  src/main/kotlin/byeonghee/week61/도넛 행성.kt
  src/main/kotlin/byeonghee/week61/무인도 여행.kt
  src/main/kotlin/byeonghee/week61/파일 합치기.kt
  src/main/kotlin/byeonghee/week61/하노이 탑.kt
Labels: 병희

#254 [장희직] - 도넛 행성, 무인도 여행, 파일 합치기3, 하노이 탑
  src/main/kotlin/heejik/61week/도넛 행성.kt
  src/main/kotlin/heejik/61week/무인도 여행.kt
  src/main/kotlin/heejik/61week/파일 합치기3.kt
  src/main/kotlin/heejik/61week/하노이 탑.kt
Labels: 희직

#259 [이지민] - Coins, 경쟁적 전염, 최소 스패닝 트리, 카드 섞기
  src/main/kotlin/jimin/62week/Coins.py
  src/main/kotlin/jimin/62week/경쟁적 전염.py
  src/main/kotlin/jimin/62week/최소 스패닝 트리.py
  src/main/kotlin/jimin/62week/카드 섞기.py
Labels: 지민

#260 [장희직] - 카드섞기 , 경쟁적 전염, coins, 최소 스패닝 트리
  src/main/kotlin/heejik/62week/Coins.kt
  src/main/kotlin/heejik/62week/경쟁적 전염.kt
  src/main/kotlin/heejik/62week/최소 스패닝 트리.kt
  src/main/kotlin/heejik/62week/카드 섞기.kt
Labels: 희직

#262 [장희직] - 괄호 제거, 도시 건설 , 싸지방에 간 준하 , 타일 채우기
  src/main/kotlin/heejik/63week/괄호 제거.py
  src/main/kotlin/heejik/63week/도시 건설.py
  src/main/kotlin/heejik/63week/싸지방에 간 준하.py
  src/main/kotlin/heejik/63week/타일 채우기.py
Labels: 희직

#263 [전현수] - 도시 건설, 괄호 제거, 싸지방에 간 준하, 타일 채우기
  src/main/kotlin/hyunsoo/63week/괄호 제거.kt
  src/main/kotlin/hyunsoo/63week/도시 건설.kt
  src/main/kotlin/hyunsoo/63week/싸지방에 간 준하.kt
  src/main/kotlin/hyunsoo/63week/타일 채우기.kt
Labels: 현수

#265 [이지민] - 싸지방에 간 준하, 도로 건설
  src/main/kotlin/jimin/63week/괄호 제거.py
  src/main/kotlin/jimin/63week/도시 건설.py
  src/main/kotlin/jimin/63week/싸지방에 간 준하.py
  src/main/kotlin/jimin/63week/타일 채우기.py
Labels: 지민

#267 [장희직] - 가장 긴 증가하는 부분 수열 4, 치즈, 삼각 달팽이, 내리막 길
  src/main/kotlin/heejik/64week/가장 긴 증가하는 부분 수열 4.kt
  src/main/kotlin/heejik/64week/내리막 길.py
  src/main/kotlin/heejik/64week/삼각 달팽이.py
  src/main/kotlin/heejik/64week/치즈.kt
Labels: 희직

#270 [소병희] - 내리막 길, 치즈, 가장 긴 증가하는 부분 수열 4, 삼각 달팽이
  src/main/kotlin/byeonghee/week64/가장 긴 증가하는 부분 수열 4.kt
  src/main/kotlin/byeonghee/week64/내리막 길.kt
  src/main/kotlin/byeonghee/week64/삼각 달팽이.kt
  src/main/kotlin/byeonghee/week64/치즈.kt
Labels: 병희
