Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2024-06, with the labels that each got.

#269 [이지민] - 가장 긴 증가하는 부분 수열 4, 치즈, 내리막 길
  src/main/kotlin/jimin/64week/가장 긴 증가하는 부분 수열 4.kt
  src/main/kotlin/jimin/64week/내리막 길.kt
  src/main/kotlin/jimin/64week/치즈.kt
Labels: 지민

#275 [소병희] - 사과나무, 후위 표기식
  src/main/kotlin/byeonghee/week65/사과나무.kt
  src/main/kotlin/byeonghee/week65/후위 표기식.kt
Labels: 병희

#274 [이지민] - 사과나무, 괄호 회전하기
  src/main/kotlin/jimin/65week/괄호 회전하기.py
  src/main/kotlin/jimin/65week/사과나무.py
Labels: 지민

#272 [전현수] - 괄호 회전하기, 후위 표기식, 캐슬 디펜스
  src/main/kotlin/hyunsoo/65week/괄호 회전하기.kt
  src/main/kotlin/hyunsoo/65week/캐슬 디펜스.kt
  src/main/kotlin/hyunsoo/65week/후위 표기식.kt
Labels: 현수

#273 [장희직] - 괄호 회전하기, 후위 표기식, 사과나무, 캐슬 디펜스
  src/main/kotlin/heejik/65week/괄호 회전하기.kt
  src/main/kotlin/heejik/65week/사과나무.kt
  src/main/kotlin/heejik/65week/캐슬 디펜스.kt
  src/main/kotlin/heejik/65week/후위 표기식.kt
Labels: 희직

#279 [이지민] - 순회강연, 용액, 맥주 마시면서 걸어가기, 혼자서 하는 틱택토
  src/main/kotlin/jimin/66week/맥주 마시면서 걸어가기.py
  src/main/kotlin/jimin/66week/순회강연.py
  src/main/kotlin/jimin/66week/용액.py
  src/main/kotlin/jimin/66week/혼자서 하는 틱택토.py
Labels: 지민

#277 [장희직] - 용액, 순회강연, 혼자서 하는 틱택톡, 맥주 마시면서 걸어다니기
  src/main/kotlin/heejik/66week/맥주 마시면서 걸어가기.py
  src/main/kotlin/heejik/66week/순회강연.kt
  src/main/kotlin/heejik/66week/용액.kt
  src/main/kotlin/heejik/66week/혼자서 하는 틱택토.kt
Labels: 희직

#280 [소병희] - 용액, 순회강연, 혼자서 하는 틱택토, 맥주 마시면서 걸어가기
  src/main/kotlin/byeonghee/week66/맥주 마시며 걸어가기.kt
  src/main/kotlin/byeonghee/week66/순회강연.kt
  src/main/kotlin/byeonghee/week66/용액.kt
  src/main/kotlin/byeonghee/week66/혼자서 하는 틱택토.kt
Labels: 병희
