Repository wellFoundedDevelopers/Algorithm, pull requests merged in 2024-02, with the labels that each got.

#208 [이지민] - 민겸 수, 이모티콘 할인 행사
  src/main/kotlin/jimin/51week/민겸 수.kt
  src/main/kotlin/jimin/51week/이모티콘 할인 행사.kt
Labels: 지민

#209 [장희직] - 민겸 수, 이모티콘 할인 행사
  src/main/kotlin/heejik/51week/k진수에서 소수 개수 구하기.kt
  src/main/kotlin/heejik/51week/거리두기 확인하기.kt
  src/main/kotlin/heejik/51week/거리두기 확인하기2.kt
  src/main/kotlin/heejik/51week/민겸 수.kt
  src/main/kotlin/heejik/51week/양궁대회.kt
  src/main/kotlin/heejik/51week/이모티콘 할인행사.kt
  src/main/kotlin/heejik/51week/주차 요금 계산.kt
Labels: 희직

#207 [소병희] - 민겸 수, 이모티콘 할인행사, 영상처리
  src/main/kotlin/byeonghee/week51/민겸 수.kt
  src/main/kotlin/byeonghee/week51/소가 길을 건너간 이유.kt
  src/main/kotlin/byeonghee/week51/영상처리.kt
  src/main/kotlin/byeonghee/week51/이모티콘 할인행사.kt
Labels: 병희
